# Environment variables
# - HOST_NAME
# - USER_NAME
# - FINGER_PRINT
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    branches:
      only:
        - develop

    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      - run:
          name: Install rsync
          command: |
            sudo apt update && sudo apt install -y rsync
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                rsync -rlOtcv --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/var/www/bottler-ai/
            fi
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       ssh ${USER_NAME}@${HOST_NAME} "sudo pip install pipenv"
      #       ssh ${USER_NAME}@${HOST_NAME} "cd /var/www/bottler-ai/ && pipenv install"
      #       ssh ${USER_NAME}@${HOST_NAME} "cd /var/www/bottler-ai/ && python manage.py runserver 0.0.0.0:8000"

